---
kind: "Template"
apiVersion: "v1"
metadata:
  name: "data-loader"
  annotations:
    description: "Job to load coops from colin into legal db"
    tags: "job"
objects:
- kind: "Job"
  apiVersion: "batch/v1"
  metadata:
    name: "data-loader"
  spec:
    template:
      spec:
        containers:
        - name: "data-loader"
          image: "docker-registry.default.svc:5000/gl2uos-tools/data-loader:${ENV_TAG}"
          imagePullPolicy: Always
          args:
          - /bin/sh
          - -c
          - cd /opt/app-root/src; ./run.sh
          env:
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  key: database-user
                  name: postgresql-${ENV_TAG}
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: database-password
                  name: postgresql-${ENV_TAG}
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  key: DATABASE_NAME
                  name: legal-api-${ENV_TAG}-config
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  key: DATABASE_HOST
                  name: legal-api-${ENV_TAG}-config
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  key: DB_PORT
                  name: legal-api-${ENV_TAG}-config
            - name: COLIN_API
              valueFrom:
                configMapKeyRef:
                  key: COLIN_URL
                  name: legal-api-${ENV_TAG}-config
            - name: AUTH_USERNAME
              valueFrom:
                secretKeyRef:
                  key: AUTH_USERNAME
                  name: updater-job
            - name: AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: AUTH_PASSWORD
                  name: updater-job
        restartPolicy: "Never"
        concurrencyPolicy: "Forbid"
parameters: [
        {
          "name": "ENV_TAG",
          "displayName": "ENV_TAG",
          "description": "the tag for the environment that the job image runs from.",
          "required": true,
          "value": "e2e"
        },
]
